name: 'Rise Version Action'
description: 'Calculates the next semVer version and outputs it.'
branding:
  icon: arrow-up
  color: green
inputs:
  suffix:
    description: 'Default - rc, options: none'
    required: false
  bump:
    description: 'No default, options: patch,minor,major'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.suffix }}
    - ${{ inputs.bump }}